-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Mar 27, 2026 at 01:03 AM
-- Server version: 9.4.0
-- PHP Version: 8.4.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `laravel`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` bigint UNSIGNED NOT NULL,
  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `short_description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` decimal(7,2) NOT NULL DEFAULT '0.00',
  `quantity` int NOT NULL DEFAULT '20',
  `image_path` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `classification` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'default' COMMENT 'default,exclusive,featured,upcoming',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `title`, `short_description`, `full_description`, `price`, `quantity`, `image_path`, `image_name`, `category`, `classification`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Alphabet Puzzle', 'Wooden Puzzles for Toddlers 3 4 5 Year Old, ABC Letter Puzzle, Educational Learning Toys for Kids Girls Boys Preschool Activities', 'Alphabet Puzzle: Package includes a puzzle board and 26 wooden uppercase letters, the alphabet puzzle size is 30 x 23.5 cm/11.81 x 9.25 in. Our abc puzzle is specially designed for kids, suitable for kids aged 3 4 5.\r\nLearning Letters and Words: This alphabet puzzle can help kids recognize letters and spell words, learn basic language skills in games, and cultivate interest in learning\r\nWooden Alphabet Puzzle: Made of wood with water-based paint on the surface, the edges are smooth and rounded without burrs. The size and thickness of the letter blocks are suitable for kids to grasp.', 52.79, 5, '/images/products/', 'AlphabetPuzzle.jpg', 'black', 'default', 'active', '2026-01-22 19:12:51', '2026-02-05 04:20:11'),
(2, 'Magnetic Blocks Building', 'SET CONTENTS: 64 magnetic building blocks in 6 vibrant colors - 12 each of blue, purple, and red, plus 10 each of orange, yellow, and green cubes.', 'CUBE DIMENSIONS: Each cube measures 1.5 inches on all sides, perfect size for little hands while maintaining building stability.\r\n\r\nENGAGING FEATURES: Blocks contain rattling elements for added sensory play and feature strong magnets that click together satisfyingly.\r\n\r\nCREATIVE PLAY: Includes idea sheets with various building suggestions to inspire construction of colorful 3D structures and designs.\r\n\r\nBUILDING SYSTEM: Magnetic cubes connect on all sides, allowing for endless building possibilities and development of spatial thinking skills.', 52.25, 50, '/images/products/', 'ColorfulBlocks.jpg', 'white', 'default', 'active', '2025-12-17 00:05:48', '2026-02-05 04:20:11'),
(3, '2 Pack Large Construction Engineering Truck Toys', 'Moveable Claw Excavator & Lifting Back Dump Truck Toy for 3 4 5 6 7 8 Years Old Boys Kids Childs Toddlers Birthday', 'Dynamic 2-Piece Set: This construction engineering games toys set comes with an excavator and a air pressure rise and fall dump truck, providing double the construction play fun. Both vehicles feature lights and sounds, enhancing the immersive play experience for kids.(The image interface has functional videos）\r\nInteractive Features: The excavator has a 360° rotating cab and a manipulable digging arm via the side lever, enabling realistic scooping. the dump truck allows kids to lift and lower the rear bed by Continuously press the up button on the top of the car and the down button on the fuel tank position, and it comes with 20 plastic stones for loading and unloading action.\r\nInertia-Powered Action: Both the excavator and dump truck utilize inertia power. Simply give them a push, and they\'ll roll smoothly.\r\n\r\nGenerous Size: Measuring around 14 inches, these toys are large enough to make a visual impact and are easy for kids to grasp and maneuver, ensuring comfortable safe play.\r\n\r\nVersatile & Gift-Worthy: Suitable for various play scenarios, from solo adventures to group play, it helps with kids cognitive development. It’s an ideal gift choice for birthdays, holidays, Christmas, and promotes quality parent - child bonding time.', 49.89, 5, '/images/products/', 'ConstructionTruckToys.jpg', 'white', 'default', 'active', '2025-12-17 08:34:16', '2026-02-05 04:20:11'),
(4, 'Doctor Playset', 'Doug Get Well Doctor Kit, 25-Piece Toddler Doctor Play Set, Realistic Pretend Play Toys & Accessories, Preschool Toys for Girls & Boys Ages 3+', 'Imaginative Doctor Play: Kids check on patients, give pretend shots, and write prescriptions for endless imaginative medical play that sparks creativity and role-playing fun every day.\r\n\r\n25-Piece Doctor Kit: Includes stethoscope, blood pressure cuff, thermometer, syringe, hearing tester, and more, all stored in a handy tote for toy storage and on-the-go play.\r\n\r\nOpen-Ended, Screen-Free Play: Builds empathy, communication & problem-solving through preschool learning activities that encourage creativity, confidence & social interaction through pretend play.\r\n\r\nEducational Toys for Any Occasion: When buying a birthday gift & holiday gifts for kids, or rewarding little milestones, celebrate the moments that matter with Melissa and Doug toys for boys & girls.\r\n\r\nWholesome Play for 35+ Years: Melissa & Doug inspires kid-powered play with its learning toys for kids, baby & toddler toys, puzzles, games, building toys & stuffed animals, dolls, & even a doll house.', 71.99, 50, '/images/products/', 'DoctorPlayset.jpg', 'gold', 'default', 'active', '2025-12-29 01:57:49', '2026-02-05 04:20:11'),
(5, 'Junior Microscope', 'Microscope for Kids Scientific Experiment Kit', 'Complete Science Kit & Portable Design: Includes 26 accessories: prepared slides with specimens, blank slides, coverslips, droppers, tweezers, instructions, and a universal smartphone adapter for capturing photos and videos. Packed in shockproof, drop‑resistant packaging for safe storage and easy carrying — perfect for school, home, or outdoor science adventures.\r\n\r\nDual LED Illumination & 7‑Color Filter Wheel : Features top LED light for opaque objects like coins and gems, and bottom LED light for transparent specimens like plant cells. The touch‑control brightness adjustment and rotating 7‑color filter disk enhance contrast, block ambient light, and improve viewing comfort.\r\n\r\nCrystal‑Clear Viewing Experience : Larger‑diameter eyepieces and professional‑grade objective lenses provide a wide, comfortable field of view. Smooth focusing wheels and adjustable lighting help kids easily achieve bright, realistic, and clear images for better observation results.\r\n\r\nEducational STEM Learning Tool: Ideal microscope for kids ages 6–12 and teens 13–16, this beginner microscope encourages curiosity, scientific observation, and hands‑on learning. Great for home education, school labs, and science projects — a versatile STEM gift that inspires a lifelong interest in science.', 68.99, 50, '/images/products/', 'JuniorMicroscope.jpg', 'gold', 'default', 'active', '2025-12-27 12:54:08', '2026-02-05 04:20:11'),
(6, 'Language Learning Kits', 'Spanish and English Talking Flash Cards for Ages 2+, Pocket Speech Therapy Tools with 510 Words.', 'Spanish and English Learning: This educational tool helps children learn two languages simultaneously, fostering their appreciation for diverse cultures, creating a fun and relaxed language learning environment, and boosting their interest in learning.\r\n\r\nProfessional Clear Voice: This talking flash cards reader has a clear voice with a standard American accent. It supports pure English, pure Spanish, and simultaneous playback of English and Spanish. Press and hold the \"Repeat\" and \"Volume\" buttons for 3 seconds to switch language modes.\r\n\r\nEnhance Cognitive Abilities: The learning tool for toddlers 2+ is rich in content, including numbers, shapes, colors, animals, transportation, and more. Help children to recognize and differentiate between different things and enhance cognitive abilities.', 37.22, 50, '/images/products/', 'LanguageLearningKits.jpg', 'silver', 'default', 'active', '2025-12-06 11:45:22', '2026-02-05 04:20:11'),
(7, 'Pattern Blocks', 'attern Blocks and Boards with 120 Multi-Colored Wooden Shape Tiles, 5 Double-Sided Puzzle', 'Skill-Building Pattern Play: Kids sort & stack wooden shaped tiles, to fill 5 unique patterns allowing them to discover & solve multiple pattern-based puzzles through hands-on developmental play.\r\n\r\nMontessori Learning Activity: Includes 120 wooden tiles in various shapes, sizes & colors, 5 double-sided puzzle boards, & a portable toy storage box, for years of immersive play with these toddler learning toys.\r\n\r\nOpen-Ended, Screen-Free Play: Develop spatial awareness, hand-eye coordination, and early math skills through preschool learning activities like sorting, matching, and visual problem-solving with tactile wooden toys.\r\n\r\nEducational Toys for Any Occasion: When buying a birthday gift & holiday gifts for kids, or rewarding little milestones, celebrate the moments that matter with Melissa and Doug toys for boys & girls.', 59.99, 10, '/images/products/', 'PatternBlocks.jpg', 'black', 'default', 'active', NULL, NULL),
(8, 'Soft Building Blocks', 'Large Building Foam Blocks for Toddlers.', 'Large Building Blocks Set – Lolo Toys Large Foam Blocks Set features Giant Foam Blocks for kids in 6 different colors and ideally sized for children to enhance fine motor skills; Each foam block set comes with a clear zippered bag to keep your jumbo blocks portable and neatly organized; These jumbo foam blocks include a variety of shapes and colors to foster imagination giving children endless possibilities of building configurations.', 39.99, 5, '/images/products/', 'SoftBuildingBlocks.jpg', 'black', 'default', 'active', NULL, NULL),
(9, 'Nesting Cups', 'First Years Stack & Count Stacking Cups - Colorful Baby Stacking Water Toys Set - Stackable Cups for Learning - Baby Bath Toys - Toddler Water Table Toys - 8 Count', 'Colorful Baby Toys: This set of stacking toys features 8 brightly colored cups that stack together with unique holes in the bottom for pouring and water play at bath time.\r\n\r\nMontessori Stacking Toys: Your kids will love creating a rainbow in the water by fitting the cups together, stacking them up, or turning them over and hiding treasures underneath.\r\n\r\nBaby Development Toys: Each of these stacking cups doubles as baby learning toys by featuring features large numbers on the bottom to help toddlers practice counting', 24.99, 20, '/images/products/', 'NestingCups.jpg', '', 'default', 'active', NULL, NULL),
(10, 'Radio Scooter', 'Durable Wheels and Frame, Converts Easily with Flip Deck, Toddler Ride On Toys ', '\r\nSTABLE AND DURABLE: Built with a sturdy frame and a 4-wheel base, this scooter for toddlers provides extra stability for beginner riders. Kids build balance and confidence while parents enjoy lasting quality that provides years of fun.\r\n\r\nGREAT BEGINNER RIDE: Designed for toddlers ages 1-4, this versatile scooter is the perfect first ride-on and scooter combo, providing active play and an easy transition from seated scooting to big-kid riding.', 74.99, 3, '/images/products/', 'RadioScooter.jpg', '', 'default', 'active', NULL, NULL),
(11, 'Robotics Kit', 'STEM Robot Building Kit, 560 PCS APP/Remote Control Mech RC Robotics for Kids Ages 8-12, Science Kit Coding Robots Toy Set', 'Realistic Features Spark ImaginationThe robot kit includes a flexible left arm, rotating right-arm turret linked to moving tracks, and an adjustable head. These dynamic functions add depth to play, making it one of the most engaging robot toys for kids 8-12.\r\n\r\nRemote & APP Controlled Robot Toy With 2.4GHz remote and Bluetooth APP control, kids enjoy responsive 360° movement indoors or outdoors. A thrilling robotics for kids ages 8-12 that inspires active, screen-free adventure on any surface.\r\n\r\nRechargeable Battery with Long Playtime Equipped with a high-capacity LiPo battery and USB Type-C cable, this RC robot runs up to 50 minutes per charge. Say goodbye to frequent battery changes and hello to uninterrupted, imaginative play.\r\n', 99.99, 10, '/images/products/', 'RoboticsKit.jpg', '', 'default', 'active', NULL, NULL),
(12, 'Shapeand Color Matching Eggs', 'Matched Eggs Toddler Toys 1 2 3 4 Year Old - Shape Color Sorting Games, Kids Easter Eggs, Toddler Sensory Toys, Preschool Educational Boy Toy, Gifts for Baby 6-12 Months+', 'Toy Eggs for Kids: The sorting toys(12.3*2.3*4.6 in) has 12 eggs that stored in 1 egg-box, designed with 6 color and 6 shapes. Toddler toys learning for 3 4 5 6 7 8 year old and shapes toys for babies, for the cute appearance can attracts kids\' attention.\r\n\r\nLearn Through Playing: The play eggs for kids are easy to open by kids\' small hands, and the 12 colorful eggs toys for kids have matched shapes and colors. By counting the shape games and sorting games, kids learn color and shape recoginition by toy eggs.\r\n\r\nEasy for Storage: Our egg sensory toy features easy storage and portable that egg toys for kids can be stored in the box. The sensory eggs for toddlers develop kids\' skills of storage. Good indoor or outdoor sorting activities for toddler learning games', 39.99, 10, '/images/products/', 'ShapeandColorMatchingEggs.jpg', '', 'default', 'active', NULL, NULL),
(13, 'Stacking Rings', 'Rainbow Stacker Wooden Ring Educational Toy - Wooden Stacking Rings, Stacker Toys for Toddlers Ages 2+.', 'This classic stacking toy features smooth, easy-to-grasp wooden pieces to stack on a solid-wood rocking base.\r\n\r\nIncludes 7 brightly colored rings, a red topper piece, and solid wood rod on a rocking wooden base.\r\n\r\nMade from durable and child-safe materials, delivering exceptional quality and value', 19.99, 20, '/images/products/', 'StackingRings.jpg', '', 'default', 'active', NULL, NULL),
(14, 'Tool Bench', 'Tool Bench for Kids Toy Play Workbench Wooden Tool Bench Workshop Workbench with Tools Set Wooden Construction Bench Toy for 3 4 5 Year Boys Girls.', 'Toy Workbench - This wooden workbench including a hammer, saw, screwdriver, wrench, vise,screws, nuts, bolts, gears, links and more creative parts for building. Kids can work on together for hours,This is a fun process that develops your little one’s motor skills and hand-eye coordination.\r\n\r\nInspire Child\'s Imagination Hand-on Ability-This kids wooden workbench is suitable for children\'s early learning and play, helping children learn to use the wrench and screw driver . Assembling nuts and bolts encourages fine motor skills,logical thinking and problem solving. developing hand-eye coordination and creativity, encouraging them to build their own projects with their own brains.\r\n\r\nChild Safety Materils-The toy workbench with high-quality beech, each part is finely treated, will not hurt child\'s hand. With healthy non-irritating odor of environmentally friendly water paint, harmless to human body. Wear-resistant, aging-resistant, safer to use. Its bright colors and gadgets stimulate children\'s senses.', 99.99, 10, '/images/products/', 'ToolBench.jpg', '', 'default', 'active', NULL, NULL),
(15, 'Wooden Vanity Table', 'Spirich Kids Vanity, Girls Vanity Set with Mirror and Stool and Lights, Kids Vanity Table.', '\r\nQUALITY AND SAFETY MATERIAL Our little girl vanity made of quality manufactured wood, sturdy and durable, white painted makeup vanity for kids with smooth and wear-resistant surface, certified by ASTM, CPSIA and CPC, It is free from harmful toxins and meet safety standards to ensure the well-being of your children.\r\n\r\nADORABLE FLOWER-SHAPED DESIGN This lovely floral vanity table and chair set comes in a sweet pink-and-white color mix that’s soft and eye-catching. It has a cute flower-shaped mirror and playful leaf-shaped shelves that make getting ready extra fun. Your little princess is sure to fall in love with it!\r\n\r\nMULTIPLE STORAGE SPACE Our little girls vanity set with stool is equipped with spacious tabletop, two leaf shape shelf on the both side, 1 drawer for your little one to sort beauty, cosmetics, Nail polish or other small belongings. this kids vanity with lights not only keep everything organized and easy to reach, make your kids bedroom more tidy and clean. but also helps to cultivate the habit of organizing things.\r\n\r\nPERFECT GIFT FOR LITTLE GIRLS This kids\' makeup desk is a wonderful addition to your child\'s bedroom or playroom. A perfect gift idea for birthdays, Christmas, or as a surprise. Its cute and stylish design is sure to delight.', 109.99, 50, '/images/products/', 'WoodenVanityTable.jpg', '', 'default', 'active', NULL, NULL),
(16, 'Shape Sorter', 'Toys for 1+ Year Old, Wooden Sorter Cube with 8pcs Rattling Shapes, Developmental Learning Toy Gifts for Baby Toddler Boys Girls, Gift Packaging', 'ENGAGING SHAPE SORTER The wooden shape sorter cube toys contain 8 diverse shapes in different colors and a sturdy box with colored rubber bands and shape holes on both sides, where kids can push the shapes in through the soft and elastic rubber bands or corresponding holes. Great toys to provide hands-on, screen-free fun for your baby.\r\n\r\nSAFETY ASSURANCE The shapes are sized for little hands yet chunky to avoid swallowing. The activity cube toys are made of durable wood and coated with non-toxic water paint. The surfaces are smooth, the corners are round, and the rubber bands are soft, protecting baby’s delicate skin.\r\n\r\nIDEAL GIFT Comes in best in class packaging for gifting, this wooden shape sorter cube makes a great first gift for your little one on birthday, Christmas, etc. Buy now to get: (1) wooden shape*8, (2) wooden box*1, and 24-hour warm and timely customer service.\r\n', 28.99, 10, '/images/products/', 'ShapeSorter.jpg', '', 'default', 'active', NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
